# Generated by Django 5.0 on 2024-05-19 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_alter_product_quantity_alter_product_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecom.payment'),
            preserve_default=False,
        ),
    ]
