# Generated by Django 5.0 on 2024-05-19 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_notification_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-date']},
        ),
    ]
