# Generated by Django 5.0 on 2024-05-20 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0009_productsize'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAtribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute', to='ecom.product')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductSize',
        ),
    ]
