# Generated by Django 5.0 on 2024-05-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0010_productatribute_delete_productsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
