# Generated by Django 5.0 on 2024-05-20 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0012_alter_product_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2024, 5, 20, 13, 8, 4, 908750, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
